package org.bouncycastle.asn1.nsri;

import o.RoundedCornersDrawable;
import o.setGlobalLegacyVisibilityHandlingEnabled;
import org.bouncycastle.asn1.ASN1ObjectIdentifier;

/* loaded from: /tmp/toss_alldex/classes30.dex */
public interface NSRIObjectIdentifiers {
    public static final ASN1ObjectIdentifier id_algorithm;
    public static final ASN1ObjectIdentifier id_aria128_cbc;
    public static final ASN1ObjectIdentifier id_aria128_ccm;
    public static final ASN1ObjectIdentifier id_aria128_cfb;
    public static final ASN1ObjectIdentifier id_aria128_cmac;
    public static final ASN1ObjectIdentifier id_aria128_ctr;
    public static final ASN1ObjectIdentifier id_aria128_ecb;
    public static final ASN1ObjectIdentifier id_aria128_gcm;
    public static final ASN1ObjectIdentifier id_aria128_kw;
    public static final ASN1ObjectIdentifier id_aria128_kwp;
    public static final ASN1ObjectIdentifier id_aria128_ocb2;
    public static final ASN1ObjectIdentifier id_aria128_ofb;
    public static final ASN1ObjectIdentifier id_aria192_cbc;
    public static final ASN1ObjectIdentifier id_aria192_ccm;
    public static final ASN1ObjectIdentifier id_aria192_cfb;
    public static final ASN1ObjectIdentifier id_aria192_cmac;
    public static final ASN1ObjectIdentifier id_aria192_ctr;
    public static final ASN1ObjectIdentifier id_aria192_ecb;
    public static final ASN1ObjectIdentifier id_aria192_gcm;
    public static final ASN1ObjectIdentifier id_aria192_kw;
    public static final ASN1ObjectIdentifier id_aria192_kwp;
    public static final ASN1ObjectIdentifier id_aria192_ocb2;
    public static final ASN1ObjectIdentifier id_aria192_ofb;
    public static final ASN1ObjectIdentifier id_aria256_cbc;
    public static final ASN1ObjectIdentifier id_aria256_ccm;
    public static final ASN1ObjectIdentifier id_aria256_cfb;
    public static final ASN1ObjectIdentifier id_aria256_cmac;
    public static final ASN1ObjectIdentifier id_aria256_ctr;
    public static final ASN1ObjectIdentifier id_aria256_ecb;
    public static final ASN1ObjectIdentifier id_aria256_gcm;
    public static final ASN1ObjectIdentifier id_aria256_kw;
    public static final ASN1ObjectIdentifier id_aria256_kwp;
    public static final ASN1ObjectIdentifier id_aria256_ocb2;
    public static final ASN1ObjectIdentifier id_aria256_ofb;
    public static final ASN1ObjectIdentifier id_pad;
    public static final ASN1ObjectIdentifier id_pad_1;
    public static final ASN1ObjectIdentifier id_pad_null;
    public static final ASN1ObjectIdentifier id_sea;
    public static final ASN1ObjectIdentifier nsri;

    static {
        ASN1ObjectIdentifier aSN1ObjectIdentifier = new ASN1ObjectIdentifier("1.2.410.200046");
        nsri = aSN1ObjectIdentifier;
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch = aSN1ObjectIdentifier.branch(setGlobalLegacyVisibilityHandlingEnabled.CERTIFY_ALL);
        id_algorithm = aSN1ObjectIdentifierBranch;
        ASN1ObjectIdentifier aSN1ObjectIdentifierBranch2 = aSN1ObjectIdentifierBranch.branch(setGlobalLegacyVisibilityHandlingEnabled.CERTIFY_ALL);
        id_sea = aSN1ObjectIdentifierBranch2;
        id_pad = aSN1ObjectIdentifierBranch.branch(setGlobalLegacyVisibilityHandlingEnabled.CERTIFY_FRONT_PASSWORD);
        id_pad_null = aSN1ObjectIdentifierBranch.branch(setGlobalLegacyVisibilityHandlingEnabled.CERTIFY_CVC);
        id_pad_1 = aSN1ObjectIdentifierBranch.branch(setGlobalLegacyVisibilityHandlingEnabled.CERTIFY_ALL);
        id_aria128_ecb = aSN1ObjectIdentifierBranch2.branch(setGlobalLegacyVisibilityHandlingEnabled.CERTIFY_ALL);
        id_aria128_cbc = aSN1ObjectIdentifierBranch2.branch(setGlobalLegacyVisibilityHandlingEnabled.CERTIFY_FRONT_PASSWORD);
        id_aria128_cfb = aSN1ObjectIdentifierBranch2.branch("3");
        id_aria128_ofb = aSN1ObjectIdentifierBranch2.branch("4");
        id_aria128_ctr = aSN1ObjectIdentifierBranch2.branch("5");
        id_aria192_ecb = aSN1ObjectIdentifierBranch2.branch("6");
        id_aria192_cbc = aSN1ObjectIdentifierBranch2.branch("7");
        id_aria192_cfb = aSN1ObjectIdentifierBranch2.branch("8");
        id_aria192_ofb = aSN1ObjectIdentifierBranch2.branch("9");
        id_aria192_ctr = aSN1ObjectIdentifierBranch2.branch(RoundedCornersDrawable.CHARGE_TYPE_NORMAL);
        id_aria256_ecb = aSN1ObjectIdentifierBranch2.branch("11");
        id_aria256_cbc = aSN1ObjectIdentifierBranch2.branch("12");
        id_aria256_cfb = aSN1ObjectIdentifierBranch2.branch("13");
        id_aria256_ofb = aSN1ObjectIdentifierBranch2.branch("14");
        id_aria256_ctr = aSN1ObjectIdentifierBranch2.branch("15");
        id_aria128_cmac = aSN1ObjectIdentifierBranch2.branch("21");
        id_aria192_cmac = aSN1ObjectIdentifierBranch2.branch("22");
        id_aria256_cmac = aSN1ObjectIdentifierBranch2.branch("23");
        id_aria128_ocb2 = aSN1ObjectIdentifierBranch2.branch("31");
        id_aria192_ocb2 = aSN1ObjectIdentifierBranch2.branch("32");
        id_aria256_ocb2 = aSN1ObjectIdentifierBranch2.branch("33");
        id_aria128_gcm = aSN1ObjectIdentifierBranch2.branch("34");
        id_aria192_gcm = aSN1ObjectIdentifierBranch2.branch("35");
        id_aria256_gcm = aSN1ObjectIdentifierBranch2.branch("36");
        id_aria128_ccm = aSN1ObjectIdentifierBranch2.branch("37");
        id_aria192_ccm = aSN1ObjectIdentifierBranch2.branch("38");
        id_aria256_ccm = aSN1ObjectIdentifierBranch2.branch("39");
        id_aria128_kw = aSN1ObjectIdentifierBranch2.branch("40");
        id_aria192_kw = aSN1ObjectIdentifierBranch2.branch("41");
        id_aria256_kw = aSN1ObjectIdentifierBranch2.branch("42");
        id_aria128_kwp = aSN1ObjectIdentifierBranch2.branch("43");
        id_aria192_kwp = aSN1ObjectIdentifierBranch2.branch("44");
        id_aria256_kwp = aSN1ObjectIdentifierBranch2.branch("45");
    }
}
