package o;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;

/* loaded from: /tmp/toss_alldex/classes13.dex */
public final class getCloseButton {
    public static final Map<CharSequence, CharSequence> IAuthTabCallback;
    public static final Map<CharSequence, CharSequence> IAuthTabCallbackDefault;
    public static final Map<CharSequence, CharSequence> IAuthTabCallbackStub;
    public static final Map<CharSequence, CharSequence> asBinder;
    public static final Map<CharSequence, CharSequence> asInterface;
    public static final Map<CharSequence, CharSequence> onExtraCallback;
    public static final Map<CharSequence, CharSequence> onExtraCallbackWithResult;
    public static final Map<CharSequence, CharSequence> onNavigationEvent;
    public static final Map<CharSequence, CharSequence> onTransact;
    public static final Map<CharSequence, CharSequence> onWarmupCompleted;

    static {
        HashMap map = new HashMap();
        map.put(" ", "&nbsp;");
        map.put("¡", "&iexcl;");
        map.put("¢", "&cent;");
        map.put("£", "&pound;");
        map.put("¤", "&curren;");
        map.put("¥", "&yen;");
        map.put("¦", "&brvbar;");
        map.put("§", "&sect;");
        map.put("¨", "&uml;");
        map.put("©", "&copy;");
        map.put("ª", "&ordf;");
        map.put("«", "&laquo;");
        map.put("¬", "&not;");
        map.put("\u00ad", "&shy;");
        map.put("®", "&reg;");
        map.put("¯", "&macr;");
        map.put("°", "&deg;");
        map.put("±", "&plusmn;");
        map.put("²", "&sup2;");
        map.put("³", "&sup3;");
        map.put("´", "&acute;");
        map.put("µ", "&micro;");
        map.put("¶", "&para;");
        map.put("·", "&middot;");
        map.put("¸", "&cedil;");
        map.put("¹", "&sup1;");
        map.put("º", "&ordm;");
        map.put("»", "&raquo;");
        map.put("¼", "&frac14;");
        map.put("½", "&frac12;");
        map.put("¾", "&frac34;");
        map.put("¿", "&iquest;");
        map.put("À", "&Agrave;");
        map.put("Á", "&Aacute;");
        map.put("Â", "&Acirc;");
        map.put("Ã", "&Atilde;");
        map.put("Ä", "&Auml;");
        map.put("Å", "&Aring;");
        map.put("Æ", "&AElig;");
        map.put("Ç", "&Ccedil;");
        map.put("È", "&Egrave;");
        map.put("É", "&Eacute;");
        map.put("Ê", "&Ecirc;");
        map.put("Ë", "&Euml;");
        map.put("Ì", "&Igrave;");
        map.put("Í", "&Iacute;");
        map.put("Î", "&Icirc;");
        map.put("Ï", "&Iuml;");
        map.put("Ð", "&ETH;");
        map.put("Ñ", "&Ntilde;");
        map.put("Ò", "&Ograve;");
        map.put("Ó", "&Oacute;");
        map.put("Ô", "&Ocirc;");
        map.put("Õ", "&Otilde;");
        map.put("Ö", "&Ouml;");
        map.put("×", "&times;");
        map.put("Ø", "&Oslash;");
        map.put("Ù", "&Ugrave;");
        map.put("Ú", "&Uacute;");
        map.put("Û", "&Ucirc;");
        map.put("Ü", "&Uuml;");
        map.put("Ý", "&Yacute;");
        map.put("Þ", "&THORN;");
        map.put("ß", "&szlig;");
        map.put("à", "&agrave;");
        map.put("á", "&aacute;");
        map.put("â", "&acirc;");
        map.put("ã", "&atilde;");
        map.put("ä", "&auml;");
        map.put("å", "&aring;");
        map.put("æ", "&aelig;");
        map.put("ç", "&ccedil;");
        map.put("è", "&egrave;");
        map.put("é", "&eacute;");
        map.put("ê", "&ecirc;");
        map.put("ë", "&euml;");
        map.put("ì", "&igrave;");
        map.put("í", "&iacute;");
        map.put("î", "&icirc;");
        map.put("ï", "&iuml;");
        map.put("ð", "&eth;");
        map.put("ñ", "&ntilde;");
        map.put("ò", "&ograve;");
        map.put("ó", "&oacute;");
        map.put("ô", "&ocirc;");
        map.put("õ", "&otilde;");
        map.put("ö", "&ouml;");
        map.put("÷", "&divide;");
        map.put("ø", "&oslash;");
        map.put("ù", "&ugrave;");
        map.put("ú", "&uacute;");
        map.put("û", "&ucirc;");
        map.put("ü", "&uuml;");
        map.put("ý", "&yacute;");
        map.put("þ", "&thorn;");
        map.put("ÿ", "&yuml;");
        Map<CharSequence, CharSequence> mapUnmodifiableMap = Collections.unmodifiableMap(map);
        asInterface = mapUnmodifiableMap;
        IAuthTabCallbackDefault = Collections.unmodifiableMap(onNavigationEvent(mapUnmodifiableMap));
        HashMap map2 = new HashMap();
        map2.put("ƒ", "&fnof;");
        map2.put("Α", "&Alpha;");
        map2.put("Β", "&Beta;");
        map2.put("Γ", "&Gamma;");
        map2.put("Δ", "&Delta;");
        map2.put("Ε", "&Epsilon;");
        map2.put("Ζ", "&Zeta;");
        map2.put("Η", "&Eta;");
        map2.put("Θ", "&Theta;");
        map2.put("Ι", "&Iota;");
        map2.put("Κ", "&Kappa;");
        map2.put("Λ", "&Lambda;");
        map2.put("Μ", "&Mu;");
        map2.put("Ν", "&Nu;");
        map2.put("Ξ", "&Xi;");
        map2.put("Ο", "&Omicron;");
        map2.put("Π", "&Pi;");
        map2.put("Ρ", "&Rho;");
        map2.put("Σ", "&Sigma;");
        map2.put("Τ", "&Tau;");
        map2.put("Υ", "&Upsilon;");
        map2.put("Φ", "&Phi;");
        map2.put("Χ", "&Chi;");
        map2.put("Ψ", "&Psi;");
        map2.put("Ω", "&Omega;");
        map2.put("α", "&alpha;");
        map2.put("β", "&beta;");
        map2.put("γ", "&gamma;");
        map2.put("δ", "&delta;");
        map2.put("ε", "&epsilon;");
        map2.put("ζ", "&zeta;");
        map2.put("η", "&eta;");
        map2.put("θ", "&theta;");
        map2.put("ι", "&iota;");
        map2.put("κ", "&kappa;");
        map2.put("λ", "&lambda;");
        map2.put("μ", "&mu;");
        map2.put("ν", "&nu;");
        map2.put("ξ", "&xi;");
        map2.put("ο", "&omicron;");
        map2.put("π", "&pi;");
        map2.put("ρ", "&rho;");
        map2.put("ς", "&sigmaf;");
        map2.put("σ", "&sigma;");
        map2.put("τ", "&tau;");
        map2.put("υ", "&upsilon;");
        map2.put("φ", "&phi;");
        map2.put("χ", "&chi;");
        map2.put("ψ", "&psi;");
        map2.put("ω", "&omega;");
        map2.put("ϑ", "&thetasym;");
        map2.put("ϒ", "&upsih;");
        map2.put("ϖ", "&piv;");
        map2.put("•", "&bull;");
        map2.put("…", "&hellip;");
        map2.put("′", "&prime;");
        map2.put("″", "&Prime;");
        map2.put("‾", "&oline;");
        map2.put("⁄", "&frasl;");
        map2.put("℘", "&weierp;");
        map2.put("ℑ", "&image;");
        map2.put("ℜ", "&real;");
        map2.put("™", "&trade;");
        map2.put("ℵ", "&alefsym;");
        map2.put("←", "&larr;");
        map2.put("↑", "&uarr;");
        map2.put("→", "&rarr;");
        map2.put("↓", "&darr;");
        map2.put("↔", "&harr;");
        map2.put("↵", "&crarr;");
        map2.put("⇐", "&lArr;");
        map2.put("⇑", "&uArr;");
        map2.put("⇒", "&rArr;");
        map2.put("⇓", "&dArr;");
        map2.put("⇔", "&hArr;");
        map2.put("∀", "&forall;");
        map2.put("∂", "&part;");
        map2.put("∃", "&exist;");
        map2.put("∅", "&empty;");
        map2.put("∇", "&nabla;");
        map2.put("∈", "&isin;");
        map2.put("∉", "&notin;");
        map2.put("∋", "&ni;");
        map2.put("∏", "&prod;");
        map2.put("∑", "&sum;");
        map2.put("−", "&minus;");
        map2.put("∗", "&lowast;");
        map2.put("√", "&radic;");
        map2.put("∝", "&prop;");
        map2.put("∞", "&infin;");
        map2.put("∠", "&ang;");
        map2.put("∧", "&and;");
        map2.put("∨", "&or;");
        map2.put("∩", "&cap;");
        map2.put("∪", "&cup;");
        map2.put("∫", "&int;");
        map2.put("∴", "&there4;");
        map2.put("∼", "&sim;");
        map2.put("≅", "&cong;");
        map2.put("≈", "&asymp;");
        map2.put("≠", "&ne;");
        map2.put("≡", "&equiv;");
        map2.put("≤", "&le;");
        map2.put("≥", "&ge;");
        map2.put("⊂", "&sub;");
        map2.put("⊃", "&sup;");
        map2.put("⊄", "&nsub;");
        map2.put("⊆", "&sube;");
        map2.put("⊇", "&supe;");
        map2.put("⊕", "&oplus;");
        map2.put("⊗", "&otimes;");
        map2.put("⊥", "&perp;");
        map2.put("⋅", "&sdot;");
        map2.put("⌈", "&lceil;");
        map2.put("⌉", "&rceil;");
        map2.put("⌊", "&lfloor;");
        map2.put("⌋", "&rfloor;");
        map2.put("〈", "&lang;");
        map2.put("〉", "&rang;");
        map2.put("◊", "&loz;");
        map2.put("♠", "&spades;");
        map2.put("♣", "&clubs;");
        map2.put("♥", "&hearts;");
        map2.put("♦", "&diams;");
        map2.put("Œ", "&OElig;");
        map2.put("œ", "&oelig;");
        map2.put("Š", "&Scaron;");
        map2.put("š", "&scaron;");
        map2.put("Ÿ", "&Yuml;");
        map2.put("ˆ", "&circ;");
        map2.put("˜", "&tilde;");
        map2.put("\u2002", "&ensp;");
        map2.put("\u2003", "&emsp;");
        map2.put("\u2009", "&thinsp;");
        map2.put("\u200c", "&zwnj;");
        map2.put("\u200d", "&zwj;");
        map2.put("\u200e", "&lrm;");
        map2.put("\u200f", "&rlm;");
        map2.put("–", "&ndash;");
        map2.put("—", "&mdash;");
        map2.put("‘", "&lsquo;");
        map2.put("’", "&rsquo;");
        map2.put("‚", "&sbquo;");
        map2.put("“", "&ldquo;");
        map2.put("”", "&rdquo;");
        map2.put("„", "&bdquo;");
        map2.put("†", "&dagger;");
        map2.put("‡", "&Dagger;");
        map2.put("‰", "&permil;");
        map2.put("‹", "&lsaquo;");
        map2.put("›", "&rsaquo;");
        map2.put("€", "&euro;");
        Map<CharSequence, CharSequence> mapUnmodifiableMap2 = Collections.unmodifiableMap(map2);
        onNavigationEvent = mapUnmodifiableMap2;
        asBinder = Collections.unmodifiableMap(onNavigationEvent(mapUnmodifiableMap2));
        HashMap map3 = new HashMap();
        map3.put("\"", "&quot;");
        map3.put("&", "&amp;");
        map3.put("<", "&lt;");
        map3.put(">", "&gt;");
        Map<CharSequence, CharSequence> mapUnmodifiableMap3 = Collections.unmodifiableMap(map3);
        onExtraCallback = mapUnmodifiableMap3;
        onExtraCallbackWithResult = Collections.unmodifiableMap(onNavigationEvent(mapUnmodifiableMap3));
        HashMap map4 = new HashMap();
        map4.put("'", "&apos;");
        Map<CharSequence, CharSequence> mapUnmodifiableMap4 = Collections.unmodifiableMap(map4);
        onWarmupCompleted = mapUnmodifiableMap4;
        IAuthTabCallback = Collections.unmodifiableMap(onNavigationEvent(mapUnmodifiableMap4));
        HashMap map5 = new HashMap();
        map5.put("\b", "\\b");
        map5.put("\n", "\\n");
        map5.put("\t", "\\t");
        map5.put("\f", "\\f");
        map5.put("\r", "\\r");
        Map<CharSequence, CharSequence> mapUnmodifiableMap5 = Collections.unmodifiableMap(map5);
        onTransact = mapUnmodifiableMap5;
        IAuthTabCallbackStub = Collections.unmodifiableMap(onNavigationEvent(mapUnmodifiableMap5));
    }

    public static Map<CharSequence, CharSequence> onNavigationEvent(Map<CharSequence, CharSequence> map) {
        return (Map) map.entrySet().stream().collect(Collectors.toMap(new Function() { // from class: org.apache.commons.text.translate.EntityArrays$$ExternalSyntheticLambda0
            @Override // java.util.function.Function
            public final Object apply(Object obj) {
                return (CharSequence) ((Map.Entry) obj).getValue();
            }
        }, new Function() { // from class: org.apache.commons.text.translate.EntityArrays$$ExternalSyntheticLambda1
            @Override // java.util.function.Function
            public final Object apply(Object obj) {
                return (CharSequence) ((Map.Entry) obj).getKey();
            }
        }));
    }
}
