#!/system/bin/sh
/data/local/tmp/magisk resetprop ro.bootimage.build.tags release-keys
/data/local/tmp/magisk resetprop ro.bootimage.build.type user
/data/local/tmp/magisk resetprop ro.odm.build.tags release-keys
/data/local/tmp/magisk resetprop ro.odm.build.type user
/data/local/tmp/magisk resetprop ro.product.bootimage.brand samsung
/data/local/tmp/magisk resetprop ro.product.bootimage.manufacturer samsung
/data/local/tmp/magisk resetprop ro.product.build.tags release-keys
/data/local/tmp/magisk resetprop ro.product.build.type user
/data/local/tmp/magisk resetprop ro.product.odm.brand samsung
/data/local/tmp/magisk resetprop ro.product.odm.manufacturer samsung
/data/local/tmp/magisk resetprop ro.product.product.brand samsung
/data/local/tmp/magisk resetprop ro.product.product.manufacturer samsung
/data/local/tmp/magisk resetprop ro.product.system.brand samsung
/data/local/tmp/magisk resetprop ro.product.system.manufacturer samsung
/data/local/tmp/magisk resetprop ro.product.system_dlkm.brand samsung
/data/local/tmp/magisk resetprop ro.product.system_dlkm.manufacturer samsung
/data/local/tmp/magisk resetprop ro.product.system_ext.brand samsung
/data/local/tmp/magisk resetprop ro.product.system_ext.manufacturer samsung
/data/local/tmp/magisk resetprop ro.product.vendor.brand samsung
/data/local/tmp/magisk resetprop ro.product.vendor.manufacturer samsung
/data/local/tmp/magisk resetprop ro.product.vendor_dlkm.brand samsung
/data/local/tmp/magisk resetprop ro.product.vendor_dlkm.manufacturer samsung
/data/local/tmp/magisk resetprop ro.system.build.tags release-keys
/data/local/tmp/magisk resetprop ro.system.build.type user
/data/local/tmp/magisk resetprop ro.system_dlkm.build.tags release-keys
/data/local/tmp/magisk resetprop ro.system_dlkm.build.type user
/data/local/tmp/magisk resetprop ro.system_ext.build.tags release-keys
/data/local/tmp/magisk resetprop ro.system_ext.build.type user
/data/local/tmp/magisk resetprop ro.vendor.build.tags release-keys
/data/local/tmp/magisk resetprop ro.vendor.build.type user
/data/local/tmp/magisk resetprop ro.vendor_dlkm.build.tags release-keys
/data/local/tmp/magisk resetprop ro.vendor_dlkm.build.type user
