package com.bytedance.sdk.openadsdk.common;

import android.R;
import android.content.Context;
import android.graphics.Color;
import android.graphics.PorterDuff;
import android.text.TextUtils;
import android.util.AttributeSet;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;
import com.bytedance.sdk.openadsdk.core.lt.dj;
import com.bytedance.sdk.openadsdk.core.lt.lt;
import com.bytedance.sdk.openadsdk.core.lt.lud;
import com.bytedance.sdk.openadsdk.utils.dc;
import com.bytedance.sdk.openadsdk.utils.ea;
import com.bytedance.sdk.openadsdk.utils.wie;

/* loaded from: /tmp/toss_alldex/classes19.dex */
public class jw extends RelativeLayout {
    public jw(Context context) {
        super(context);
        ycx();
    }

    private void ycx() {
        setId(wie.nzi);
        setBackgroundColor(-1);
        Context context = getContext();
        setLayoutParams(new ViewGroup.LayoutParams(-1, dc.zb(context, 44.0f)));
        int iZb = dc.zb(context, 10.0f);
        int iZb2 = dc.zb(context, 24.0f);
        dj djVar = new dj(context);
        int i2 = wie.wk;
        djVar.setId(i2);
        djVar.setClickable(true);
        djVar.setFocusable(true);
        djVar.setImageResource(com.bytedance.sdk.component.utils.wwx.dj(context, "tt_titlebar_close_new"));
        ImageView.ScaleType scaleType = ImageView.ScaleType.CENTER_INSIDE;
        djVar.setScaleType(scaleType);
        djVar.setAdjustViewBounds(true);
        RelativeLayout.LayoutParams layoutParams = new RelativeLayout.LayoutParams(iZb2, iZb2);
        layoutParams.addRule(9);
        layoutParams.addRule(15);
        layoutParams.setMargins(iZb, iZb, iZb, iZb);
        addView((View) djVar, (ViewGroup.LayoutParams) layoutParams);
        dj djVar2 = new dj(context);
        int i3 = wie.dfk;
        djVar2.setId(i3);
        djVar2.setClickable(true);
        djVar2.setFocusable(true);
        djVar2.setImageResource(com.bytedance.sdk.component.utils.wwx.dj(context, "tt_titlebar_backward"));
        djVar2.setScaleType(scaleType);
        RelativeLayout.LayoutParams layoutParams2 = new RelativeLayout.LayoutParams(iZb2, iZb2);
        layoutParams2.addRule(1, i2);
        layoutParams2.addRule(15);
        int i4 = iZb << 1;
        layoutParams2.setMargins(i4, iZb, iZb, iZb);
        addView((View) djVar2, (ViewGroup.LayoutParams) layoutParams2);
        lud ludVar = new lud(context);
        ludVar.setId(wie.zk);
        ludVar.setOrientation(1);
        ludVar.setGravity(17);
        com.bytedance.sdk.openadsdk.core.lt.fby fbyVar = new com.bytedance.sdk.openadsdk.core.lt.fby(context);
        fbyVar.setId(wie.ycx);
        fbyVar.setSingleLine(true);
        TextUtils.TruncateAt truncateAt = TextUtils.TruncateAt.END;
        fbyVar.setEllipsize(truncateAt);
        fbyVar.setTextColor(Color.parseColor("#222222"));
        fbyVar.setTextSize(2, 14.0f);
        fbyVar.setGravity(17);
        com.bytedance.sdk.openadsdk.core.lt.fby fbyVar2 = new com.bytedance.sdk.openadsdk.core.lt.fby(context);
        fbyVar2.setId(wie.zb);
        fbyVar2.setSingleLine(true);
        fbyVar2.setEllipsize(truncateAt);
        fbyVar2.setTextColor(Color.argb(122, 0, 0, 0));
        fbyVar2.setTextSize(2, 12.0f);
        fbyVar2.setGravity(16);
        fbyVar2.setPadding(0, 0, 0, 0);
        fbyVar2.setIncludeFontPadding(false);
        lud ludVar2 = new lud(context);
        ludVar2.setOrientation(0);
        ludVar2.setGravity(16);
        dj djVar3 = new dj(context);
        int iDj = com.bytedance.sdk.component.utils.wwx.dj(context, "tt_titlebar_lock");
        if (iDj != 0) {
            djVar3.setImageResource(iDj);
            int iZb3 = dc.zb(context, 12.0f);
            LinearLayout.LayoutParams layoutParams3 = new LinearLayout.LayoutParams(iZb3, iZb3);
            layoutParams3.rightMargin = dc.zb(context, 4.0f);
            djVar3.setLayoutParams(layoutParams3);
            djVar3.setColorFilter(Color.argb(122, 0, 0, 0), PorterDuff.Mode.SRC_IN);
            ludVar2.addView(djVar3);
        }
        ludVar.addView(fbyVar, new LinearLayout.LayoutParams(-2, -2));
        ViewGroup.LayoutParams layoutParams4 = new LinearLayout.LayoutParams(-2, -2);
        ludVar2.addView(fbyVar2, layoutParams4);
        ludVar.addView(ludVar2, layoutParams4);
        RelativeLayout.LayoutParams layoutParams5 = new RelativeLayout.LayoutParams(-2, -2);
        layoutParams5.addRule(1, i3);
        int i5 = wie.vyl;
        layoutParams5.addRule(0, i5);
        layoutParams5.addRule(15);
        layoutParams5.setMargins(iZb, 0, iZb, 0);
        addView((View) ludVar, (ViewGroup.LayoutParams) layoutParams5);
        dj djVar4 = new dj(context);
        djVar4.setId(i5);
        djVar4.setClickable(true);
        djVar4.setFocusable(true);
        djVar4.setImageResource(com.bytedance.sdk.component.utils.wwx.dj(context, "tt_titlebar_forward"));
        djVar4.setScaleType(scaleType);
        RelativeLayout.LayoutParams layoutParams6 = new RelativeLayout.LayoutParams(iZb2, iZb2);
        layoutParams6.addRule(0, 520093740);
        layoutParams6.addRule(15);
        layoutParams6.setMargins(iZb, iZb, i4, iZb);
        addView((View) djVar4, (ViewGroup.LayoutParams) layoutParams6);
        dj djVar5 = new dj(context);
        djVar5.setId(520093740);
        djVar5.setClickable(true);
        djVar5.setFocusable(true);
        djVar5.setImageResource(com.bytedance.sdk.component.utils.wwx.dj(context, "tt_history_titlebar_delete"));
        djVar5.setScaleType(scaleType);
        RelativeLayout.LayoutParams layoutParams7 = new RelativeLayout.LayoutParams(iZb2, iZb2);
        layoutParams7.addRule(11);
        layoutParams7.addRule(15);
        layoutParams7.setMargins(iZb, iZb, iZb, iZb);
        addView((View) djVar5, (ViewGroup.LayoutParams) layoutParams7);
        View ltVar = new lt(context, (AttributeSet) null, R.style.Widget.ProgressBar.Horizontal);
        ltVar.setId(wie.qn);
        ltVar.setProgress(1);
        ltVar.setProgressDrawable(ea.ycx(context, "tt_privacy_progress_style"));
        RelativeLayout.LayoutParams layoutParams8 = new RelativeLayout.LayoutParams(-1, dc.zb(context, 2.0f));
        layoutParams8.addRule(12);
        addView(ltVar, layoutParams8);
        View view = new View(context);
        view.setBackgroundColor(Color.parseColor("#1F161823"));
        RelativeLayout.LayoutParams layoutParams9 = new RelativeLayout.LayoutParams(-1, dc.zb(context, 0.5f));
        layoutParams9.addRule(12);
        addView(view, layoutParams9);
        djVar2.setClickable(false);
        djVar4.setClickable(false);
        int color = Color.parseColor("#A8FFFFFF");
        PorterDuff.Mode mode = PorterDuff.Mode.ADD;
        djVar2.setColorFilter(color, mode);
        djVar4.setColorFilter(Color.parseColor("#A8FFFFFF"), mode);
    }
}
